apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: survey-app
type: Opaque
stringData:
  mysql-root-password: password
  mysql-database: survey_db
  mysql-user: survey
  mysql-password: survey_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: survey-app
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: password
  DB_HOST: mysql-service
  DB_NAME: survey_db

